global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "account-spring"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "account-spring"

  - job_name: "transfer-spring"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "transfer-spring"

  - job_name: "account-micronaut"
    metrics_path: /prometheus
    static_configs:
      - targets: ["host.docker.internal:8082"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "account-micronaut"

  - job_name: "transfer-micronaut"
    metrics_path: /prometheus
    static_configs:
      - targets: ["host.docker.internal:8083"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "transfer-micronaut"
